# Generated by Django 5.2.4 on 2025-09-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_blogcategory_projectcategory_alter_blogpost_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sociallink",
            name="platform",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook"),
                    ("twitter", "Twitter"),
                    ("linkedin", "LinkedIn"),
                    ("github", "GitHub"),
                    ("instagram", "Instagram"),
                    ("youtube", "YouTube"),
                    ("whatsapp", "Whatsapp"),
                    ("telegram", "Telegram"),
                ],
                max_length=50,
            ),
        ),
    ]
