# Generated by Django 4.2 on 2025-11-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_testimonial_approved_testimonial_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="image",
            field=models.ImageField(
                blank=True,
                default="images/default_testimonial.png",
                null=True,
                upload_to="images/",
            ),
        ),
    ]
