# Generated by Django 4.2 on 2025-11-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_testimonial_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testimonial",
            name="image",
        ),
    ]
