# Generated by Django 4.2 on 2025-11-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_remove_testimonial_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="testimonials/"),
        ),
    ]
